name: ci

on:
  push:
    branches:
      - 'gitflow'

# list of jobs
jobs:
  # first job: 'docker' is the name of this job.
  docker:
    runs-on: ubuntu-latest
    # this job contains 3 steps
    steps:
      -
        name: Set up QEMU
        # https://github.com/marketplace/actions/docker-setup-qemu
        # set up more platforms (default = all)
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        # https://github.com/marketplace/actions/docker-setup-buildx
        # set up a multi-platform builder for Docker containers
        uses: docker/setup-buildx-action@v2
      -
        name: test secret
        run: printenv        
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      -
        name: Login to DockerHub
        # https://github.com/marketplace/actions/docker-login
        # login to DockerHub with secrets login & token
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        # https://github.com/marketplace/actions/build-and-push-docker-images
        # this job build the docker image and push into Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: resources
          push: true
          tags: pifou25/lgthinq:latest
