name: Semantic Release

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ none ]
  # this is to manually trigger the worklow
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        default: 'Manual launch'

jobs:
  # one single job
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        # https://github.com/marketplace/actions/action-for-semantic-release
        uses: cycjimmy/semantic-release-action@v3
        # id is required for output variables
        # https://github.com/marketplace/actions/action-for-semantic-release#outputs
        id: semantic 
        with:
          semantic_version: 19  # v20 is incompatible with Github Action as it required node18
          branches: |
            [
              'master',
              {
                name: 'dev',
                prerelease: true
              },
              {
                name: 'test',
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @google/semantic-release-replace-plugin
          dry_run: false
          working_directory: .
          tag_format: '${version}' # default is v{version}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Github summary
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "New release : ${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_STEP_SUMMARY
